pipeline:
  publish:
    image: plugins/docker
    registry: no-cloud.fr
    repo: no-cloud.fr/maestro/spectrum
    tag: latest
    file: Dockerfile

  notify:
    image: no-cloud.fr/drone/xmpp
    jid: ${XMPP_JID}
    password: ${XMPP_PASSWORD}
    to_jid: arnaud@arnaudbouts.fr
    message: >
      maestro-spectrum build finished with ${DRONE_JOB_STATUS} status.
