pipeline:
  publish:
    image: plugins/docker
    registry: no-cloud.fr
    repo: no-cloud.fr/maestro/spectrum
    tag: latest
    file: Dockerfile

  notify:
    image: no-cloud.fr/drone-xmpp
    secrets: [ xmpp_jid, xmpp_password, xmpp_to ]
    when:
      status: [ success, failure ]
