pipeline:
  publish:
    image: plugins/docker
    registry: no-cloud.fr
    repo: no-cloud.fr/maestro/spectrum
    tag: debian
    file: Dockerfile

  notify-ok:
    image: no-cloud.fr/drone/xmpp
    jid: ${XMPP_JID}
    password: ${XMPP_PASSWORD}
    to_jid: arnaud@arnaudbouts.fr
    message: "maestro-spectrum build finished with success status."
    when:
      status: [ success ]

  notify-ko:
    image: no-cloud.fr/drone/xmpp
    jid: ${XMPP_JID}
    password: ${XMPP_PASSWORD}
    to_jid: arnaud@arnaudbouts.fr
    message: "maestro-spectrum build finished with failure status."
    when:
      status: [ failure ]

